/* Generated By:JJTree: Do not edit this line. F:\p4\depot\Ascape\src\com\nutech\ascape\query\parser\BoolExprTreeTreeConstants.java */

package org.ascape.query.parser;

public interface BoolExprTreeTreeConstants
{
  public int JJTINPUT = 0;
  public int JJTBOOLEANPHRASE = 1;
  public int JJTVOID = 2;
  public int JJTBOOLEANAND = 3;
  public int JJTBOOLEANOR = 4;
  public int JJTCRITERIA = 5;
  public int JJTPROPERTY = 6;
  public int JJTWILDCARD = 7;
  public int JJTFIELD = 8;
  public int JJTEQUAL = 9;
  public int JJTNOTEQUAL = 10;
  public int JJTLESSTHAN = 11;
  public int JJTGREATERTHAN = 12;
  public int JJTSTARTSWITH = 13;
  public int JJTCONTAINS = 14;
  public int JJTNONQUOTEDSTRING = 15;
  public int JJTNUMBERSTRING = 16;
  public int JJTQUOTEDSTRING = 17;


  public String[] jjtNodeName = {
    "Input",
    "BooleanPhrase",
    "void",
    "BooleanAnd",
    "BooleanOr",
    "Criteria",
    "Property",
    "WildCard",
    "Field",
    "Equal",
    "NotEqual",
    "LessThan",
    "GreaterThan",
    "StartsWith",
    "Contains",
    "NonQuotedString",
    "NumberString",
    "QuotedString",
  };
}
