/* Generated By:JJTree&JavaCC: Do not edit this line. BoolExprTreeConstants.java */
package org.ascape.query.parser;

public interface BoolExprTreeConstants {

  int EOF = 0;
  int QUOTED_STRING = 5;
  int AND = 6;
  int OR = 7;
  int EQUAL = 8;
  int NOT_EQUAL = 9;
  int LESS_THAN = 10;
  int GREATER_THAN = 11;
  int STARTS_WITH = 12;
  int CONTAINS = 13;
  int WILDCARD = 14;
  int PERIOD = 15;
  int NAME = 16;
  int NUMBER = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<QUOTED_STRING>",
    "<AND>",
    "<OR>",
    "<EQUAL>",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "<STARTS_WITH>",
    "<CONTAINS>",
    "\"*\"",
    "\".\"",
    "<NAME>",
    "<NUMBER>",
    "\"(\"",
    "\")\"",
  };

}
