/* Generated By:JJTree: Do not edit this line. QTBooleanPhrase.java */

package org.ascape.query.parser;

public class QTBooleanPhrase extends SimpleNode {
  public QTBooleanPhrase(int id) {
    super(id);
  }

  public QTBooleanPhrase(BoolExprTree p, int id) {
    super(p, id);
  }

    public boolean evaluate(Object object) {
        boolean result = true;
        for (int i = 0; i < jjtGetNumChildren(); i = i + 2) {
            //todo at some point we could optimize this by sorting so that ands come first
            boolean currentResult;
            if (jjtGetChild(i) instanceof QTBooleanPhrase) {
                currentResult = ((QTBooleanPhrase) jjtGetChild(i)).evaluate(object);
            } else if (jjtGetChild(i) instanceof QTCriteria) {
                currentResult = ((QTCriteria) jjtGetChild(i)).evaluate(object);
            } else {
                throw new InternalError("Bad parse of query part: " + this);
            }
            if ((i == 0) || (jjtGetChild(i - 1) instanceof QTBooleanAnd)) {
                result = result && currentResult;
            } else if (jjtGetChild(i - 1) instanceof QTBooleanOr) {
                result = result || currentResult;
            } else {
                throw new InternalError("Bad parse of query part: " + this);
            }
        }
        return result;
    }
}
