/* Generated By:JJTree: Do not edit this line. QTBooleanAnd.java */

package org.ascape.query.parser;

public class QTBooleanAnd extends SimpleNode {
    public QTBooleanAnd(int id) {
        super(id);
    }

    public QTBooleanAnd(BoolExprTree p, int id) {
        super(p, id);
    }

    public String toString() {
        return "AND";
    }

}
