/* Generated By:JJTree: Do not edit this line. QTBooleanOr.java */

package org.ascape.query.parser;

public class QTBooleanOr extends SimpleNode {
    public QTBooleanOr(int id) {
        super(id);
    }

    public QTBooleanOr(BoolExprTree p, int id) {
        super(p, id);
    }

    public String toString() {
        return "OR";
    }

}
