/* Generated By:JJTree: Do not edit this line. QTComparisonOperator.java */

package org.ascape.query.parser;

public class QTComparisonOperator extends SimpleNode {
    public QTComparisonOperator(int id) {
        super(id);
    }

    public QTComparisonOperator(BoolExprTree p, int id) {
        super(p, id);
    }

}
