/* Generated By:JJTree: Do not edit this line. QTContains.java */

package org.ascape.query.parser;

public class QTContains extends QTStringOperatorNode {
    public QTContains(int id) {
        super(id);
    }

    public QTContains(BoolExprTree p, int id) {
        super(p, id);
    }

    public String toString() {
        return "contains";
    }

    public boolean evaluate(QTValue compared, Object value) {
        //todo is there some way to do this inexpensivly while ignoring case?
        return ((String) value).indexOf((String) compared.getCoercedValue()) >= 0;
    }
}
