/* Generated By:JJTree: Do not edit this line. QTCriteria.java */

package org.ascape.query.parser;

import org.ascape.query.Validated;

public class QTCriteria extends SimpleNode implements Validated {

    public QTCriteria(int id) {
        super(id);
    }

    public QTCriteria(BoolExprTree p, int id) {
        super(p, id);
    }

    public void validate(Object object) throws ParseException {
    }

    public QTProperty getProperty() {
        return (QTProperty) jjtGetChild(0);
    }

    public QTOperator getOperator() {
        return (QTOperator) jjtGetChild(1);
    }

    public QTValue getValue() {
        return (QTValue) jjtGetChild(2);
    }

    public boolean evaluate(Object object) {
        try {
            return getOperator().evaluate(getValue(), getProperty().getComparedValue(object));
        } catch (ParseException e) {
            throw new InternalError("Unexpected parse error. (Should have been caught by validate): " + e);
        }
    }
}
