/* Generated By:JJTree: Do not edit this line. QTEqual.java */

package org.ascape.query.parser;

public class QTEqual extends QTOperator {
    public QTEqual(int id) {
        super(id);
    }

    public QTEqual(BoolExprTree p, int id) {
        super(p, id);
    }

    public String toString() {
        return "equal";
    }

    public boolean evaluate(QTValue compared, Object value) {
        if (!(value instanceof String)) {
            return compared.getCoercedValue().equals(value);
        } else {
            return ((String) compared.getCoercedValue()).equalsIgnoreCase((String) value);
        }
    }
}
