/* Generated By:JJTree: Do not edit this line. QTGreaterThan.java */

package org.ascape.query.parser;

public class QTGreaterThan extends QTStringOrNumberOperatorNode {
    public QTGreaterThan(int id) {
        super(id);
    }

    public QTGreaterThan(BoolExprTree p, int id) {
        super(p, id);
    }

    public String toString() {
        return "greater than";
    }

    public boolean evaluate(QTValue compared, Object value) {
        return compared.getComparor().compareTo(value) < 0;
    }
}
