/* Generated By:JJTree: Do not edit this line. QTLessThan.java */

package org.ascape.query.parser;

public class QTLessThan extends QTStringOrNumberOperatorNode {
    public QTLessThan(int id) {
        super(id);
    }

    public QTLessThan(BoolExprTree p, int id) {
        super(p, id);
    }

    public String toString() {
        return "less than";
    }

    public boolean evaluate(QTValue compared, Object value) {
        return compared.getComparor().compareTo(value) > 0;
    }

}
