/* Generated By:JJTree: Do not edit this line. QTNotEqual.java */

package org.ascape.query.parser;

public class QTNotEqual extends QTOperator {
    public QTNotEqual(int id) {
        super(id);
    }

    public QTNotEqual(BoolExprTree p, int id) {
        super(p, id);
    }

    public String toString() {
        return "not equal";
    }

    public boolean evaluate(QTValue compared, Object value) {
        return !compared.getCoercedValue().equals(value);
    }

}
