/* Generated By:JJTree: Do not edit this line. QTNonQuotedString.java */

package org.ascape.query.parser;

public class QTNonQuotedString extends QTValue {

    public QTNonQuotedString(int id) {
        super(id);
    }

    public QTNonQuotedString(BoolExprTree p, int id) {
        super(p, id);
    }

}
