/* Generated By:JJTree: Do not edit this line. QTNumberString.java */

package org.ascape.query.parser;

public class QTNumberString extends QTValue {
  public QTNumberString(int id) {
    super(id);
  }

  public QTNumberString(BoolExprTree p, int id) {
    super(p, id);
  }

}
