/* Generated By:JJTree: Do not edit this line. QTQuotedString.java */

package org.ascape.query.parser;

public class QTQuotedString extends QTValue {

    public QTQuotedString(int id) {
        super(id);
    }

    public QTQuotedString(BoolExprTree p, int id) {
        super(p, id);
    }
}
