/* Generated By:JJTree: Do not edit this line. QTStartsWith.java */

package org.ascape.query.parser;

public class QTStartsWith extends QTStringOperatorNode {
    public QTStartsWith(int id) {
        super(id);
    }

    public QTStartsWith(BoolExprTree p, int id) {
        super(p, id);
    }

    public String toString() {
        return "starts with";
    }

    public boolean evaluate(QTValue compared, Object value) {
        return ((String) value).startsWith((String) compared.getCoercedValue());
    }
}
