/* Generated By:JJTree: Do not edit this line. QTSubExpression.java */

package org.ascape.query.parser;

public class QTSubExpression extends SimpleNode {
    public QTSubExpression(int id) {
        super(id);
    }

    public QTSubExpression(BoolExprTree p, int id) {
        super(p, id);
    }

}
