/* Generated By:JJTree: Do not edit this line. QTWildCard.java */

package org.ascape.query.parser;

public class QTWildCard extends SimpleNode {
  public QTWildCard(int id) {
    super(id);
  }

  public QTWildCard(BoolExprTree p, int id) {
    super(p, id);
  }

}
